
export enum TruckType {
  AXLE_3 = '3-Achser (10m³)',
  AXLE_4 = '4-Achser (12m³)'
}

export interface Truck {
  id: string;
  name: string;
  plate?: string;
  volume: number;
}

export interface CustomMaterial {
  id: string;
  name: string;
  colorClass: string;
}

export interface LoadingPoint {
  id: string;
  name: string;
  material: string; // Name des Materials
  latitude: number;
  longitude: number;
  radius?: number; // Optionaler individueller Radius
}

export interface Site {
  id: string;
  name: string;
  createdAt: number;
  latitude?: number;
  longitude?: number;
  radius?: number;
  loadingPoints: LoadingPoint[];
}

export interface Load {
  id: string;
  siteId: string;
  loadingPointId?: string;
  material: string; // Name des Materials
  volume: number;
  truckId?: string;
  truckName?: string; // Für Historie, falls LKW gelöscht wird
  timestamp: number;
  isAutoGenerated?: boolean;
}

export interface AppState {
  sites: Site[];
  loads: Load[];
  materials: CustomMaterial[];
  trucks: Truck[];
  activeTruckId: string | null;
  activeSiteId: string | null;
  autoDetectEnabled: boolean;
  autoCountEnabled: boolean;
}

